# This is the configuration for the experiments on March 24

parallelism : '48'
kafka_server : 'ibm-power-3:9092'
kafka_zookeeper : 'ibm-power-3:2181'
events.perstep.max : '100000'
events.perstep.low : '9999'
pause : '1000'
change_interval : '20000'
benchmark : 'nexmark'
